version: $(version).{build}
environment:
  version: 0.0.2
  state: -alpha
  public_version: $(version)$(state)
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: $(public_version)
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_build:
- cmd: >-
    7z a BandiEngine.zip %APPVEYOR_BUILD_FOLDER%\BandiEngine\bin\%CONFIGURATION%\BandiEngine.dll

    7z a BandiEngine.zip %APPVEYOR_BUILD_FOLDER%\BandiEngine\bin\%CONFIGURATION%\BandiEngine.xml
artifacts:
- path: BandiEngine\bin\$(configuration)\BandiEngine.dll
  name: BandiEngine
- path: BandiEngine\bin\$(configuration)\BandiEngine.xml
  name: BandiEngine
- path: BandiEngine.zip
  name: BandiEngine.zip
deploy:
- provider: GitHub
  tag: v$(public_version)
  release: BandiEngine v$(public_version)
  auth_token:
    secure: ywvj6v8RbrXSFRlkwpoxLg//t0/lTYZSInOT8A3YOySEJ0sS1hv3UrkksY4xJyBu
  artifact: BandiEngine.zip
  prerelease: true
  on:
    branch: master
- provider: NuGet
  api_key:
    secure: 3huCPS4uPHG8GMWkjicCs74aLRANlvHDB5OTl1A6KyhexBQogvJNeooS3po76nCV
  on:
    branch: master